import PDFDocument from 'pdfkit'

// Shared PDF report builder — used by illness handoff report, health summary, and raw data export.
// All report generators should call this class instead of touching PDFKit directly.

const COLORS = {
  heading: '#111827',
  label: '#6B7280',
  value: '#111827',
  divider: '#E5E7EB',
  accent: '#374151',
  disclaimer: '#9CA3AF',
}

const FONT_SIZES = {
  reportTitle: 18,
  subtitle: 11,
  meta: 9,
  sectionHeading: 10,
  body: 9.5,
  small: 8.5,
}

export type ReportMeta = Array<[string, string]>

export class PdfReportBuilder {
  private doc: InstanceType<typeof PDFDocument>
  private buffers: Buffer[] = []
  private pageWidth: number
  private marginLeft: number
  private marginRight: number
  private contentWidth: number
  private disclaimer: string

  constructor(disclaimer = 'Generated by private family tracker — not an official medical record.') {
    this.doc = new PDFDocument({
      size: 'LETTER',
      margin: 50,
      // bufferPages required for switchToPage to work in toBuffer footer loop
      bufferPages: true,
      info: { Producer: 'Baby Tracker', Creator: 'Baby Tracker' },
    })
    this.marginLeft = 50
    this.marginRight = 50
    this.pageWidth = this.doc.page.width
    this.contentWidth = this.pageWidth - this.marginLeft - this.marginRight
    this.disclaimer = disclaimer

    this.doc.on('data', (chunk: Buffer) => this.buffers.push(chunk))
  }

  addReportHeader(title: string, subtitle: string, meta: ReportMeta = []): this {
    const doc = this.doc

    doc.fontSize(FONT_SIZES.reportTitle).font('Helvetica-Bold').fillColor(COLORS.heading)
    doc.text(title, this.marginLeft, 50, { width: this.contentWidth })

    doc.moveDown(0.3)
    doc.fontSize(FONT_SIZES.subtitle).font('Helvetica').fillColor(COLORS.label)
    doc.text(subtitle, { width: this.contentWidth })

    if (meta.length > 0) {
      doc.moveDown(0.4)
      doc.fontSize(FONT_SIZES.meta).font('Helvetica').fillColor(COLORS.label)
      for (const [label, value] of meta) {
        doc.text(`${label}  ${value}`, { width: this.contentWidth })
      }
    }

    this.addDivider(true)
    return this
  }

  addSectionHeading(title: string): this {
    const doc = this.doc
    doc.moveDown(0.6)
    doc.fontSize(FONT_SIZES.sectionHeading).font('Helvetica-Bold').fillColor(COLORS.accent)
    doc.text(title.toUpperCase(), this.marginLeft, undefined, {
      width: this.contentWidth,
      characterSpacing: 0.5,
    })
    doc.moveDown(0.2)
    this.addDivider()
    doc.moveDown(0.3)
    return this
  }

  addKeyValue(label: string, value: string): this {
    const doc = this.doc
    const labelWidth = 130
    const valueX = this.marginLeft + labelWidth
    const valueWidth = this.contentWidth - labelWidth

    const y = doc.y
    doc.fontSize(FONT_SIZES.body).font('Helvetica-Bold').fillColor(COLORS.label)
    doc.text(label, this.marginLeft, y, { width: labelWidth, lineBreak: false })
    doc.fontSize(FONT_SIZES.body).font('Helvetica').fillColor(COLORS.value)
    doc.text(value, valueX, y, { width: valueWidth })
    return this
  }

  addBulletList(items: string[]): this {
    const doc = this.doc
    doc.fontSize(FONT_SIZES.body).font('Helvetica').fillColor(COLORS.value)
    for (const item of items) {
      doc.text(`• ${item}`, this.marginLeft + 8, undefined, { width: this.contentWidth - 8 })
    }
    return this
  }

  addTextBlock(text: string): this {
    this.doc.fontSize(FONT_SIZES.body).font('Helvetica').fillColor(COLORS.value)
    this.doc.text(text, this.marginLeft, undefined, { width: this.contentWidth })
    return this
  }

  addTable(headers: string[], rows: string[][], colWidths?: number[]): this {
    const doc = this.doc
    const cols = headers.length
    const widths = colWidths ?? headers.map(() => this.contentWidth / cols)
    // Explicit line heights so we can advance doc.y manually.
    // PDFKit advances y after every doc.text() call regardless of lineBreak:false,
    // so each cell must share the same captured y and we set doc.y explicitly after each row.
    const headerLineH = Math.ceil(FONT_SIZES.small * 1.5)
    const rowLineH = Math.ceil(FONT_SIZES.body * 1.55)

    // header row — capture y once, pass it explicitly to every cell
    doc.fontSize(FONT_SIZES.small).font('Helvetica-Bold').fillColor(COLORS.label)
    const headerY = doc.y
    let x = this.marginLeft
    for (let i = 0; i < headers.length; i++) {
      doc.text(headers[i]!, x, headerY, { width: widths[i]!, lineBreak: false })
      x += widths[i]!
    }
    doc.y = headerY + headerLineH

    // thin divider under headers
    const divY = doc.y + 2
    doc.moveTo(this.marginLeft, divY)
      .lineTo(this.pageWidth - this.marginRight, divY)
      .lineWidth(0.5).strokeColor(COLORS.divider).stroke()
    doc.y = divY + 5

    // data rows — same pattern: one captured y per row
    doc.fontSize(FONT_SIZES.body).font('Helvetica').fillColor(COLORS.value)
    for (const row of rows) {
      const rowY = doc.y
      x = this.marginLeft
      for (let i = 0; i < row.length; i++) {
        doc.text(row[i] ?? '', x, rowY, { width: widths[i]!, lineBreak: false })
        x += widths[i]!
      }
      doc.y = rowY + rowLineH
    }
    return this
  }

  addDivider(thick = false): this {
    const doc = this.doc
    const y = doc.y
    doc.moveTo(this.marginLeft, y)
      .lineTo(this.pageWidth - this.marginRight, y)
      .lineWidth(thick ? 1 : 0.5)
      .strokeColor(COLORS.divider)
      .stroke()
    doc.moveDown(0.3)
    return this
  }

  addSpacer(lines = 0.5): this {
    this.doc.moveDown(lines)
    return this
  }

  toBuffer(): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      // Stamp the disclaimer footer onto every buffered page before flushing.
      // bufferPages:true in the constructor is required for this to work.
      const range = this.doc.bufferedPageRange()
      for (let i = range.start; i < range.start + range.count; i++) {
        this.doc.switchToPage(i)
        this.doc
          .fontSize(FONT_SIZES.small)
          .font('Helvetica')
          .fillColor(COLORS.disclaimer)
          .text(
            this.disclaimer,
            this.marginLeft,
            this.doc.page.height - 40,
            { width: this.contentWidth, align: 'center', lineBreak: false },
          )
      }

      this.doc.on('end', () => resolve(Buffer.concat(this.buffers)))
      this.doc.on('error', reject)
      this.doc.flushPages()
      this.doc.end()
    })
  }
}

// Helpers shared across text-format report renderers

export function textDivider(char = '─', width = 60): string {
  return char.repeat(width)
}

export function textKeyValue(label: string, value: string, labelWidth = 20): string {
  return `${label.padEnd(labelWidth)}${value}`
}

export function textSectionHeading(title: string): string {
  return `\n${textDivider()}\n${title.toUpperCase()}\n${textDivider()}`
}
